import type {NextPage} from "next";
import Head from "next/head";
import Login from "./login";
import {ChakraProvider} from "@chakra-ui/react";
import Register from "./register";

import Link from "next/link";

const Home: NextPage = () => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <ChakraProvider>
        <Register />
      </ChakraProvider>
    </div>
  );
};

export default Home;
